name: flutter_hrm_inventory_pos_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.7.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/menu/
    - assets/icons
    - assets/icons/alert/
    - assets/icons/nav/
