class StaffMemberModel {
  final String imageUrl;
  final String warehouse;
  final String role;
  final String name;
  final String username;
  final String email;
  final String phone;
  final String status;
  final String departement;
  final String designation;
  final String shift;
  final String address;

  StaffMemberModel({
    required this.imageUrl,
    required this.warehouse,
    required this.role,
    required this.name,
    required this.username,
    required this.email,
    required this.phone,
    required this.status,
    required this.departement,
    required this.designation,
    required this.shift,
    required this.address,
  });

  bool get isEnabe => status == 'Enable';
}

final List<StaffMemberModel> staffMembers = [
  StaffMemberModel(
    imageUrl: 'https://assets.ggwp.id/2023/06/R-1-640x360.jpg',
    warehouse: 'Gudang A',
    role: 'Supervisor',
    name: 'Budi Santoso',
    username: '@budisantoso',
    email: 'budi.santoso@jagoflutter.id',
    phone: '+628123456789',
    status: 'Enable',
    departement: 'Operasional',
    designation: 'Mobile Developer',
    shift: 'Pagi',
    address: 'Jl. Merdeka No.1, Jakarta',
  ),
  StaffMemberModel(
    imageUrl: 'https://assets.ggwp.id/2023/06/R-1-640x360.jpg',
    warehouse: 'Gudang B',
    role: 'Staff',
    name: 'Siti Aminah',
    username: '@sitiaminah',
    email: 'siti.aminah@jagoflutter.id',
    phone: '+628987654321',
    status: 'Enable',
    departement: 'Pemasaran',
    designation: 'Mobile Developer',
    shift: 'Siang',
    address: 'Jl. Sudirman No.2, Bandung',
  ),
  StaffMemberModel(
    imageUrl: 'https://assets.ggwp.id/2023/06/R-1-640x360.jpg',
    warehouse: 'Gudang C',
    role: 'Operator',
    name: 'Andi Wijaya',
    username: '@andiwijaya',
    email: 'andi.wijaya@jagoflutter.id',
    phone: '+628112233445',
    status: 'Disable',
    departement: 'Produksi',
    designation: 'Mobile Developer',
    shift: 'Malam',
    address: 'Jl. Gajah Mada No.3, Surabaya',
  ),
  StaffMemberModel(
    imageUrl: 'https://assets.ggwp.id/2023/06/R-1-640x360.jpg',
    warehouse: 'Gudang D',
    role: 'Admin',
    name: 'Dewi Lestari',
    username: '@dewilestari',
    email: 'dewi.lestari@jagoflutter.id',
    phone: '+628223344556',
    status: 'Enable',
    departement: 'Keuangan',
    designation: 'Mobile Developer',
    shift: 'Pagi',
    address: 'Jl. Diponegoro No.4, Yogyakarta',
  ),
  StaffMemberModel(
    imageUrl: 'https://assets.ggwp.id/2023/06/R-1-640x360.jpg',
    warehouse: 'Gudang E',
    role: 'Security',
    name: 'Rudi Hartono',
    username: '@rudihartono',
    email: 'rudi.hartono@jagoflutter.id',
    phone: '+628334455667',
    status: 'Disable',
    departement: 'Keamanan',
    designation: 'Mobile Developer',
    shift: 'Siang',
    address: 'Jl. Pattimura No.5, Semarang',
  ),
  StaffMemberModel(
    imageUrl: 'https://assets.ggwp.id/2023/06/R-1-640x360.jpg',
    warehouse: 'Gudang A',
    role: 'Supervisor',
    name: 'Budi Santoso',
    username: '@budisantoso',
    email: 'budi.santoso@jagoflutter.id',
    phone: '+628123456789',
    status: 'Enable',
    departement: 'Operasional',
    designation: 'Mobile Developer',
    shift: 'Pagi',
    address: 'Jl. Merdeka No.1, Jakarta',
  ),
  StaffMemberModel(
    imageUrl: 'https://assets.ggwp.id/2023/06/R-1-640x360.jpg',
    warehouse: 'Gudang B',
    role: 'Staff',
    name: 'Siti Aminah',
    username: '@sitiaminah',
    email: 'siti.aminah@jagoflutter.id',
    phone: '+628987654321',
    status: 'Enable',
    departement: 'Pemasaran',
    designation: 'Mobile Developer',
    shift: 'Siang',
    address: 'Jl. Sudirman No.2, Bandung',
  ),
  StaffMemberModel(
    imageUrl: 'https://assets.ggwp.id/2023/06/R-1-640x360.jpg',
    warehouse: 'Gudang C',
    role: 'Operator',
    name: 'Andi Wijaya',
    username: '@andiwijaya',
    email: 'andi.wijaya@jagoflutter.id',
    phone: '+628112233445',
    status: 'Disable',
    departement: 'Produksi',
    designation: 'Mobile Developer',
    shift: 'Malam',
    address: 'Jl. Gajah Mada No.3, Surabaya',
  ),
  StaffMemberModel(
    imageUrl: 'https://assets.ggwp.id/2023/06/R-1-640x360.jpg',
    warehouse: 'Gudang D',
    role: 'Admin',
    name: 'Dewi Lestari',
    username: '@dewilestari',
    email: 'dewi.lestari@jagoflutter.id',
    phone: '+628223344556',
    status: 'Enable',
    departement: 'Keuangan',
    designation: 'Mobile Developer',
    shift: 'Pagi',
    address: 'Jl. Diponegoro No.4, Yogyakarta',
  ),
  StaffMemberModel(
    imageUrl: 'https://assets.ggwp.id/2023/06/R-1-640x360.jpg',
    warehouse: 'Gudang E',
    role: 'Security',
    name: 'Rudi Hartono',
    username: '@rudihartono',
    email: 'rudi.hartono@jagoflutter.id',
    phone: '+628334455667',
    status: 'Disable',
    departement: 'Keamanan',
    designation: 'Mobile Developer',
    shift: 'Siang',
    address: 'Jl. Pattimura No.5, Semarang',
  ),
  StaffMemberModel(
    imageUrl: 'https://assets.ggwp.id/2023/06/R-1-640x360.jpg',
    warehouse: 'Gudang A',
    role: 'Supervisor',
    name: 'Budi Santoso',
    username: '@budisantoso',
    email: 'budi.santoso@jagoflutter.id',
    phone: '+628123456789',
    status: 'Enable',
    departement: 'Operasional',
    designation: 'Mobile Developer',
    shift: 'Pagi',
    address: 'Jl. Merdeka No.1, Jakarta',
  ),
  StaffMemberModel(
    imageUrl: 'https://assets.ggwp.id/2023/06/R-1-640x360.jpg',
    warehouse: 'Gudang B',
    role: 'Staff',
    name: 'Siti Aminah',
    username: '@sitiaminah',
    email: 'siti.aminah@jagoflutter.id',
    phone: '+628987654321',
    status: 'Enable',
    departement: 'Pemasaran',
    designation: 'Mobile Developer',
    shift: 'Siang',
    address: 'Jl. Sudirman No.2, Bandung',
  ),
  StaffMemberModel(
    imageUrl: 'https://assets.ggwp.id/2023/06/R-1-640x360.jpg',
    warehouse: 'Gudang C',
    role: 'Operator',
    name: 'Andi Wijaya',
    username: '@andiwijaya',
    email: 'andi.wijaya@jagoflutter.id',
    phone: '+628112233445',
    status: 'Disable',
    departement: 'Produksi',
    designation: 'Mobile Developer',
    shift: 'Malam',
    address: 'Jl. Gajah Mada No.3, Surabaya',
  ),
  StaffMemberModel(
    imageUrl: 'https://assets.ggwp.id/2023/06/R-1-640x360.jpg',
    warehouse: 'Gudang D',
    role: 'Admin',
    name: 'Dewi Lestari',
    username: '@dewilestari',
    email: 'dewi.lestari@jagoflutter.id',
    phone: '+628223344556',
    status: 'Enable',
    departement: 'Keuangan',
    designation: 'Mobile Developer',
    shift: 'Pagi',
    address: 'Jl. Diponegoro No.4, Yogyakarta',
  ),
  StaffMemberModel(
    imageUrl: 'https://assets.ggwp.id/2023/06/R-1-640x360.jpg',
    warehouse: 'Gudang E',
    role: 'Security',
    name: 'Rudi Hartono',
    username: '@rudihartono',
    email: 'rudi.hartono@jagoflutter.id',
    phone: '+628334455667',
    status: 'Disable',
    departement: 'Keamanan',
    designation: 'Mobile Developer',
    shift: 'Siang',
    address: 'Jl. Pattimura No.5, Semarang',
  ),
];
